Data - analysis

Information 

Weather information - 

day time temp pressure location ... 

Predictive analysis - analysing data to make future predictions





hard coding - delibrately writing lines of code by yourself without any assistance


arrays - C Cpp

python arrays???

inbuilt datastructure 

list an array?

list = [1,2,3,4,5]



In [ ]:
list = [[1,2,3,4,5],[1,2,3,4,5]]


type(list)

list

In [10]:
import numpy as np



In [ ]:
#numpy

list = np.array([     [[1,2],[1,2]],      [[1,2],[1,2]]    ])

print(list)

[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]


In [36]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
arr3 = np.array([1,2,3,5,6,7,8,9,10])

arr2D = np.array([[1,2,3],[4,5,6]])
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr1,"\n")

print(arr2,"\n")

print(arr2D,"\n")

print(arr3D,"\n")

[1 2 3] 

[1 2 3] 

[[1 2 3]
 [4 5 6]] 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 



In [24]:
arraySum = arr1 + arr2 # element-wise addition
arrayDiff = arr1 - arr2 # element-wise subtraction
arrayProduct = arr1 * arr2 # element-wise multiplication
arrayQuotient = arr1 / arr2 # element-wise division

print(arraySum)
print(arrayDiff)    
print(arrayProduct)
print(arrayQuotient)


[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]


In [33]:
# array properties
print(arr1.shape) # shape of the array
print(arr2D.shape) # shape of the 2D array
print(arr3D.shape) # shape of the 3D array

print(arr1.ndim) # number of dimensions of the array
print(arr2D.ndim) # number of dimensions of the 2D array
print(arr3D.ndim) # number of dimensions of the 3D array


(3,)
(2, 3)
(2, 2, 3)
1
2
3


In [ ]:
# slicing

print(arr3[0:10:3]) # slicing the array from index 0 to 10 with a step of 3  

# array[start:stop:step]

[1 5 8]


In [1]:
import pandas as pd

# vectors - one dimension arrays
data = [2,2,2,3,4,5]

series = pd.Series(data) # index is auto-generated
print(series)

0    2
1    2
2    2
3    3
4    4
5    5
dtype: int64


In [4]:
data = {
    'a': [1,2,3],    
    'b': [4,5,6],
    'c': [7,8,9],
    'd': [10,11,12],
    'e': [13,14,15],
}

df = pd.DataFrame(data) # 
print(df)

   a  b  c   d   e
0  1  4  7  10  13
1  2  5  8  11  14
2  3  6  9  12  15


In [64]:
df.to_csv('data.csv') # save the dataframe to a csv file

In [5]:
df1 = df.drop(columns=['a','b']) # drop columns a and b
print(df1)

   c   d   e
0  7  10  13
1  8  11  14
2  9  12  15


In [65]:
df3 = pd.read_csv('data.csv') # read csv file
print(df3)

   Unnamed: 0  a  b  c   d   e
0           0  1  4  7  10  13
1           1  2  5  8  11  14
2           2  3  6  9  12  15


In [9]:
df1.head()

c   d   e
0  7  10  13
1  8  11  14
2  9  12  15

In [ ]:


df1.info() # information about the dataframe, shows us the missing values and the data types of the columns
df1.describe() # gives us the summary of the dataframe, shows us the mean, std, min, max, 25%, 50%, 75% percentiles of the columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c       3 non-null      int64
 1   d       3 non-null      int64
 2   e       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes


c     d     e
count  3.0   3.0   3.0
mean   8.0  11.0  14.0
std    1.0   1.0   1.0
min    7.0  10.0  13.0
25%    7.5  10.5  13.5
50%    8.0  11.0  14.0
75%    8.5  11.5  14.5
max    9.0  12.0  15.0

info() - to get more information 

describe()

In [12]:
import pandas as pd

df = pd.read_csv('Iris.csv')

iris setosa

iris viginica

iris versicolor

--------------

species

In [ ]:
df.head() # by default shows the first 5 rows of the dataframe


# head takes an integer as an argument and shows the first n rows of the dataframe

#df.tail() # shows the last 5 rows of the dataframe

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
145  146            6.7           3.0            NaN           2.3
146  147            NaN           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  148 non-null    float64
 2   SepalWidthCm   147 non-null    float64
 3   PetalLengthCm  146 non-null    float64
 4   PetalWidthCm   150 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [ ]:
df.describe() # gives us the summary of the dataframe, shows us the statistics of the columns


# distribution - statistics

# data science - statistics - 

# AI ML Projects? Department??? CSE 



Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     148.000000    147.000000     146.000000    150.000000
mean    75.500000       5.845270      3.052381       3.717808      1.198667
std     43.445368       0.830567      0.437041       1.770006      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.525000      0.300000
50%     75.500000       5.800000      3.000000       4.250000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [33]:
# data cleaning - Topic - in the next class - 
# handling missing values - 

missing_values = df.isnull().sum()
print(missing_values) # shows the number of missing values in each column

Id               0
SepalLengthCm    2
SepalWidthCm     3
PetalLengthCm    4
PetalWidthCm     0
dtype: int64


In [ ]:
# removing missing values

# handling missing data - 

