Data - analysis

Information 

Weather information - 

day time temp pressure location ... 

Predictive analysis - analysing data to make future predictions





hard coding - delibrately writing lines of code by yourself without any assistance


arrays - C Cpp

python arrays???

inbuilt datastructure 

list an array?

list = [1,2,3,4,5]



In [ ]:
list = [[1,2,3,4,5],[1,2,3,4,5]]


type(list)

list

In [10]:
import numpy as np



In [ ]:
#numpy

list = np.array([     [[1,2],[1,2]],      [[1,2],[1,2]]    ])

print(list)

[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]


In [36]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
arr3 = np.array([1,2,3,5,6,7,8,9,10])

arr2D = np.array([[1,2,3],[4,5,6]])
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr1,"\n")

print(arr2,"\n")

print(arr2D,"\n")

print(arr3D,"\n")

[1 2 3] 

[1 2 3] 

[[1 2 3]
 [4 5 6]] 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 



In [24]:
arraySum = arr1 + arr2 # element-wise addition
arrayDiff = arr1 - arr2 # element-wise subtraction
arrayProduct = arr1 * arr2 # element-wise multiplication
arrayQuotient = arr1 / arr2 # element-wise division

print(arraySum)
print(arrayDiff)    
print(arrayProduct)
print(arrayQuotient)


[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]


In [33]:
# array properties
print(arr1.shape) # shape of the array
print(arr2D.shape) # shape of the 2D array
print(arr3D.shape) # shape of the 3D array

print(arr1.ndim) # number of dimensions of the array
print(arr2D.ndim) # number of dimensions of the 2D array
print(arr3D.ndim) # number of dimensions of the 3D array


(3,)
(2, 3)
(2, 2, 3)
1
2
3


In [ ]:
# slicing

print(arr3[0:10:3]) # slicing the array from index 0 to 10 with a step of 3  

# array[start:stop:step]

[1 5 8]


In [49]:
import pandas as pd

# vector 
data = [2,2,2,3,4,5]

series = pd.Series(data) # index is auto-generated
print(series)

0    2
1    2
2    2
3    3
4    4
5    5
dtype: int64


In [57]:
data = {
    'a': [1,2,3],    
    'b': [4,5,6],
    'c': [7,8,9],
    'd': [10,11,12],
    'e': [13,14,15],
}

df = pd.DataFrame(data) # 
print(df)

   a  b  c   d   e
0  1  4  7  10  13
1  2  5  8  11  14
2  3  6  9  12  15


In [64]:
df.to_csv('data.csv') # save the dataframe to a csv file

In [62]:
df1 = df.drop(columns=['a','b']) # drop columns a and b
print(df1)

   c   d   e
0  7  10  13
1  8  11  14
2  9  12  15


In [65]:
df3 = pd.read_csv('data.csv') # read csv file
print(df3)

   Unnamed: 0  a  b  c   d   e
0           0  1  4  7  10  13
1           1  2  5  8  11  14
2           2  3  6  9  12  15
